services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - ALLOWED_EMAILS=${ALLOWED_EMAILS}
        - ORIGIN=${ORIGIN}
        - BASELIME_API_KEY=${BASELIME_API_KEY}
    ports:
      - 3004:3000
