services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
        - DATABASE_URL=${DATABASE_URL}
        - JWT_SECRET=${JWT_SECRET}
        - ALLOWED_EMAILS=${ALLOWED_EMAILS}
        - ORIGIN=${ORIGIN}
    ports:
      - 3000:3000
