name: ⚔️ `check` before merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.2.13]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALLOWED_EMAILS: ${{ secrets.ALLOWED_EMAILS }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      BASELIME_API_KEY: ${{ secrets.BASELIME_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint command
        run: bun run lint

      - name: Run svelte-check command
        run: bun run check

      - name: Run type check
        run: bun run check:ts
