name: ⚔️ `check` before merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.2.13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint command
        run: bun run lint

      - name: Run type check
        run: bun run check:ts

      - name: Run svelte-check command
        run: bun run check
