name: ⚔️ `check` before merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run lint command
        run: bun run lint

      - name: Run check command
        run: bun run check
