name: ⚔️ `check` before merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bun-version: [1.2.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run lint command
        run: bun run lint

      # - name: Run check command
      #   run: bun run check
