name: 🧪 Unit tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.2.18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install playwright
        run: bunx playwright install --with-deps

      - name: Run tests
        run: bun run test
